### ISSUE TITLE
Questions about timezone/ZoneInfo and fold attribute

### ISSUE THREAD

**Issue by ariebovenberg** [channable/heliclockter#12]
👋 Hi there, I recently came across this nice project. As far as I know, it's the only one looking to make the aware/naive distinction at both runtime and type-checking 👏 

Looking at the code though I had some questions:

**1. The local timezone is cast to `ZoneInfo` here, but `.tzinfo` here always returns `datetime.timezone` instances.**

https://github.com/channable/heliclockter/blob/9d9443c9e78b2896b6e2d7b6c9e9e3ab6230a355/src/heliclockter/__init__.py#L45

I know because I've tried as well ;). `timezone` (e.g. CET) sadly doesn't account for variable UTC offsets (i.e. no DST), while `ZoneInfo` (e.g. `Europe/Paris`) *does*.
The solution could be to use the [tzlocal](https://github.com/regebro/tzlocal) library which helps determine the actual IANA timezone (i.e. `ZoneInfo` object) for the system. Pendulum uses this approach AFAIK.

**2. The `fold` attribute is omitted from the constructor**. Is this intentional? It's the only way to disambiguate times that occur twice is a timezone. It would be interesting if it could be omitted for the UTC datetime (which is never ambiguous), but required for IANA zoned datetimes.

😉 PS: I'm working on a datetime library [of my own](https://github.com/ariebovenberg/whenever). Feel free to drop feedback if you like 🙂

**Comment by blubberdiblub** [comment]
> **1. The local timezone is cast to `ZoneInfo` here, but `.tzinfo` here always returns `datetime.timezone` instances.**
> 
> https://github.com/channable/heliclockter/blob/9d9443c9e78b2896b6e2d7b6c9e9e3ab6230a355/src/heliclockter/__init__.py#L45
> 
> I know because I've tried as well ;). `timezone` (e.g. CET) sadly doesn't account for variable UTC offsets (i.e. no DST), while `ZoneInfo` (e.g. `Europe/Paris`) _does_. The solution could be to use the [tzlocal](https://github.com/regebro/tzlocal) library which helps determine the actual IANA timezone (i.e. `ZoneInfo` object) for the system. Pendulum uses this approach AFAIK.

Not sure about the casting to `ZoneInfo`, but aside from that as far as I'm aware `.astimezone(tz=None)` (where `tz=None` is the default when specifying no argument) is a special case and means to convert to the so-called "system" timezone (called "local" by pendulum), which is the thing handled by `time.tzset()`, `time.timezone`, `time.altzone` and `time.daylight`, respectively, and therefore **does** account for DST and **does have** a variable UTC offset (`time.timezone` vs `time.altzone` seconds) **if the "system" timezone has it**.

**Comment by ariebovenberg** [comment]
I didn't explain very well. Indeed `tz=None` results in the system timezone, but it gives a _fixed offset_ instead of the actual IANA timezone (which may have variable offset).

example for me in Europe:

```python
>>> from datetime import datetime, timezone, timedelta
>>> d = datetime(2023, 1, 1).astimezone(None)
datetime.datetime(2023, 1, 1, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600), 'CET'))
# it's correct that this is the offset _at this time_, but it's fixed
>>> timezone.__doc__
'Fixed offset from UTC implementation of tzinfo.'
# if we move to summer the offset in europe should be +2hr instead of +1hr.
# however, because `timezone` is fixed offset, this isn't correctly reflected.
>>> in_summer = d + timedelta(days=150)
>>> in_summer
datetime.datetime(2023, 5, 31, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600), 'CET'))
>>> in_summer.utcoffset()
datetime.timedelta(seconds=3600)  # incorrect. Should be +2hrs (CEST)
```

correct using IANA timezones
```python
>>> d = datetime(2023, 1, 1, tzinfo=ZoneInfo("Europe/Paris"))
>>> d.utcoffset()
datetime.timedelta(seconds=3600)  # correct -- wintertime!
>>> in_summer_correct = d + timedelta(days=150)
>>> in_summer_correct.utcoffset()
datetime.timedelta(seconds=7200)  # correct -- summertime!
```

The difference is that CET and CEST (both fixed offset) are _observed_ by "Europe/Paris". In the winter, it's CET and in the summer CEST. `timezone` object in Python cannot handle this variable offset, that is what differentiates it from `ZoneInfo`

**Comment by blubberdiblub** [comment]
@ariebovenberg 
Yeah, I see what you mean now. However, I believe this is due to the broken `dt + timedelta` handling (or call it ideosyncracy if you like) of _datetime_.

Here's the example showing that the "system" timezone does in principle have varying UTC offsets (btw, I'm in Berlin, Germany, so CET/CEST here, too):

    In [3]: datetime(2023, 1, 1).astimezone(None).utcoffset()
    Out[3]: datetime.timedelta(seconds=3600)

    In [4]: datetime(2023, 7, 1).astimezone(None).utcoffset()
    Out[4]: datetime.timedelta(seconds=7200)

**Comment by blubberdiblub** [comment]
Thinking a little more about it, I guess I was misunderstanding what you were trying to say.
Mea culpa.

Basically, what you're saying is that once you attach datetime's "system" timezone to a datetime, its offset is fixed at that time and can never change again. It's static now.

Whereas a real ZoneInfo has a dynamic offset.

Sorry again. I guess I got confused by my own implementation of a "system" timezone class, which datetime doesn't do. (mine is actually dynamic)

**Comment by ariebovenberg** [comment]
Indeed. It's a shame that `astimezone()` doesn't get us the dynamic IANA timezone. It'll probably stay like this for backwards compatibility, or the fact that it's nontrivial to determine (as evidenced by the tzlocal package). Although, it could be worth posting a ticket to CPython 🤔 

what you mention about datetime + timedelta not taking DST into account is a whole separate pitfall 😬.

**Comment by ariebovenberg** [comment]
Here is an example that would probably need to be patched:

```python
from heliclockter import datetime_local
from datetime import datetime

f1 = datetime_local.from_datetime(datetime(2024, 7, 1).astimezone())
f2 = datetime_local.from_datetime(datetime(2024, 1, 1).astimezone())
print(f1)
print(f2)
```

outputs (running the code in europe in winter):
```
2024-06-30 23:00:00+01:00
2024-01-01 00:00:00+01:00
```

And If we'd be running the code in summer, we'd get:
```
2024-07-01 23:00:00+02:00
2020-01-01 01:00:00+02:00
```


expected (year round):
```
2024-07-01 00:00:00+02:00
2024-01-01 00:00:00+01:00
```

Probably the `datetime_local` would need special logic to allow summertime/wintertime being different `timezone` values. Or: use the `tzlocal` package to bypass this entirely

**Comment by p-nilsson** [comment]
Hi @ariebovenberg thanks for your interesting questions! Let me try to elaborate on our choices.

> 1. The local timezone is cast to ZoneInfo here, but .tzinfo here always returns datetime.timezone instances.

Good point! This can definitely be seen as "wrong" since we are telling mypy the type is different than what it actually is.

> The solution could be to use the [tzlocal](https://github.com/regebro/tzlocal) library which helps determine the actual IANA timezone (i.e. ZoneInfo object) for the system.

Very true. Before open sourcing this library we did use tzinfo internally at Channable, but one of the design decisions was to make this library work with no 3rd party dependencies to make it as easy to install and use for as many people as possible. This is also the reasoning for the optional pydantic integration. We need that at Channable, but didn't want to force other developers to install pydantic just to use this library.

> 2. The fold attribute is omitted from the constructor. Is this intentional?

Good question. Very true that this might cause slight hiccups around DST changes. We have been running this code in production for upwards of 3 years now without any noticeable issues, but that doesn't mean it shouldn't or couldn't change to make the library more robust. I don't recall any deliberate decision to omit `fold` from the constructor. Maybe @jochemb remembers as we originally co-wrote this logic.

All that being said, PRs to improve the library are always welcome, of course, but please do add tests for any new functionalities added.

**Comment by p-nilsson** [comment]
> This issue is that by removing fold from the constructor, you've effectively removed functionality (seemingly) without reason.

I believe you are right. I have opened a PR to add `fold`: https://github.com/channable/heliclockter/pull/13


>  Note that pendulum seems to have completely vendored the tzlocal codebase, so that could also be an option for you to avoid 3rd party dependencies

This does seem like a possible improvement and definitely a workaround to avoid 3rd party dependencies. Personally I don't have the time at the moment to do this though

**Comment by ariebovenberg** [comment]
@p-nilsson what are your thought on [this](https://github.com/channable/heliclockter/issues/12#issuecomment-1890458692) though?

effectively the library will behave differently depending on whether you _import it_ in summer or wintertime.

```python
tz_local = cast(ZoneInfo, _datetime.datetime.now().astimezone().tzinfo) 
```

Imagine servers being automatically scaled up and down after a DST transition to summertime. "new" servers would have `tz_local` equal to CEST, while older servers (for which the code is already imported), `tz_local` would be CET.

**Comment by p-nilsson** [comment]
Ah, sorry, indeed, I can agree that that can be an issue / lead to unexpected /wrong timestamps around DST. This is mainly a problem for long running processes though. Short lived processes won't really be affected by this, although the possibility is there of course.

I agree that it is something that can and should be improved, but preferrably not by introducing a 3rd party dependency like `tzlocal`. The fastest and easiest way might be to just copy the relevant code from tzlocal, as you suggest pendulum also does

**Comment by ariebovenberg** [comment]
Understandable. Although I do want to add that it's not only about _long-running_ processes: Imagine a script used to generate a logistical planning for the upcoming week that you run each Friday. That script would generate timestamps 1 hour off for two weeks in the year 🤔

**Comment by p-nilsson** [comment]
Yes, I agree 👍 assuming you schedule that script to run around the time change 

Again, I definitely agree it can be a problem, and it is worthy of an improvement, just that with our use case it never really has been in the 3 years we have been running this code in production

**Comment by ariebovenberg** [comment]
Ok 👍. Thanks for indulging me with these questions. Feel free to close the issue when you like.

**Comment by p-nilsson** [comment]
And thank you too!

**Comment by blubberdiblub** [comment]
@ariebovenberg here's a possible implementation for `tz_local` in #14 that I believe addresses the issue you raised concerning it.
